### ISSUE TITLE
Suggestion: Allow faster food eating speed

### ISSUE THREAD

**Issue by ulk-underscore** [squeek502/SpiceOfLife#133]
...or is this already possible?
What I mean is that nutritional value at 100% means faster eating speed (maybe half?). This would serve as a reward mechanic and provide an additional immersive clue about what the food status is.

**Comment by squeek502** [comment]
This is currently possible, but with some restrictions. 

Food eating speed is based on the nutritional value of the food, so if, for example, you create a formula that starts at 200% and decreases to 100%, and you set `food.eating.speed.modifier` to 1, then your foods will take half as long to eat when the nutritional value is 200%, and the normal speed when its 100%.

However, this also would affect the food values (hunger/saturation) of foods, unless you turned all of that off (`affect.food.hunger.values`, `affect.food.saturation.modifiers`) so that *only* eating speed is affected. There's currently no way to control food values/eating speed separately.

**Comment by ulk-underscore** [comment]
It took me some time to understand the parser logic, but I think I got it.
Thanks for the help.
